dist: xenial
language: groovy
jdk:
  - openjdk8
  - openjdk9
  - openjdk10
  - openjdk11
  - openjdk12
env:
  - TEST_CATEGORY=uncategorizedTests
  - TEST_CATEGORY=widgetsetCompileTests
  - TEST_CATEGORY=themeCompileTests
  - TEST_CATEGORY=fullCompileTests
  - TEST_CATEGORY=runProjectTests
  - TEST_CATEGORY=proxyTest
script: "./gradlew --stacktrace check -PTEST_CATEGORY=$TEST_CATEGORY"
branches:
  only:
    - "master"
cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle